language: node_js
sudo: required
node_js:
  - 8.2.1
cache:
  directories:
    - node_modules
before_script:
  - git checkout gh-pages
script:
  - npm run build
after_success:
  - git add --all .
  - git commit -m "travis ci auto build"
  - git push https://github.com/vueComponent/ant-design.git gh-pages
